backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://noticereply.com"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "about.html"
        label: "About"
        name: "about"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "resources.html"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
